name: Build and Push API to ECR 
on: 
  push:
    branches:
      - main 
    paths:
      - 'api/**'
      - '.github/workflows/ci-pipeline.yaml'
env:
  AWS_REGION: ap-southeast-1  # Target deployment AWS Region
  ECR_REPOSITORY: python-api  # Target AWS ECR Repository 
jobs: 
  build-and-push:
    name: Build Docker image and push to AWS ECR 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v4 
    # Step 2: Log into AWS Account using encrypted repository secrets
      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v4 
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
    # Step 3: Authenticate the local Docker daemon aganist your private AWS registry
      - name: Login to Amazon ECR 
        id: login-ecr 
        uses: aws-actions/amazon-ecr-login@v2
    # Step 4: Build,Tag and push image
      - name: Build, Tag and push image 
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }} # Unique Git commit hash
        run: |
          # Build the container image using the context of the api/ directory
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./api 
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "::notice::Successfully built and pushed version tag:$IMAGE_TAG"
          