name: "4. Application Deployment Pipeline(Helm)"
on:
  push: 
    branches: 
      - main 
    paths:
      - 'charts/**' # Triggers if your helm chart configuration change
      
env: 
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: python-api 
  EKS_CLUSTER_NAME: production-eks-cluster
  HELM_RELEASE_NAME: smartstack-api 
  NAMESPACE: production
jobs:
  helm-deploy: 
    name: "Deploy to EKS via Helm"
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v4 
      # Step 1: Connect securely to your AWS Account 
      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get AWS Account ID
        id: aws-info
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "registry=${ACCOUNT_ID}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com" >> $GITHUB_OUTPUT
      # Extract credentials
      - name: Update Kubeconfig 
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
      - name: Set up Helm 
        uses: azure/setup-helm@v4 
        with: 
          version: 'v3.14.0'     
      # Execute an idempotent install or upgrade matching the newest ECR tag 
      - name: Helm Upgrade or Install 
        env: 
          ECR_REGISTRY: ${{ steps.aws-info.outputs.registry }} 
          DEPLOY_TAG: ${{ github.sha }}
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./charts/core-app \
            --namespace ${{ env.NAMESPACE }} \
            --create-namespace \
            --set image.repository=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }} \
            --set image.tag=$DEPLOY_TAG
